// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5I7jpL-ffTj85dqHoVZXgJ8_2kY1TNMY',
    appId: '1:871150867786:web:f3420b8ba83d5a65989db3',
    messagingSenderId: '871150867786',
    projectId: 'nssgym-c6b7e',
    authDomain: 'nssgym-c6b7e.firebaseapp.com',
    storageBucket: 'nssgym-c6b7e.firebasestorage.app',
    measurementId: 'G-11PWKHMHMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWnd6uEEf_YXFcIh5UJbKlOT4h_AReIu8',
    appId: '1:871150867786:android:011c8d45e4290451989db3',
    messagingSenderId: '871150867786',
    projectId: 'nssgym-c6b7e',
    storageBucket: 'nssgym-c6b7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqHHiwq5CSAwe8KUlJeNlCFuNep1PvaAA',
    appId: '1:871150867786:ios:4b9654372ff09f78989db3',
    messagingSenderId: '871150867786',
    projectId: 'nssgym-c6b7e',
    storageBucket: 'nssgym-c6b7e.firebasestorage.app',
    iosBundleId: 'com.example.nssGym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqHHiwq5CSAwe8KUlJeNlCFuNep1PvaAA',
    appId: '1:871150867786:ios:4b9654372ff09f78989db3',
    messagingSenderId: '871150867786',
    projectId: 'nssgym-c6b7e',
    storageBucket: 'nssgym-c6b7e.firebasestorage.app',
    iosBundleId: 'com.example.nssGym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5I7jpL-ffTj85dqHoVZXgJ8_2kY1TNMY',
    appId: '1:871150867786:web:60cf3cd301008660989db3',
    messagingSenderId: '871150867786',
    projectId: 'nssgym-c6b7e',
    authDomain: 'nssgym-c6b7e.firebaseapp.com',
    storageBucket: 'nssgym-c6b7e.firebasestorage.app',
    measurementId: 'G-KHXB1J0B7S',
  );
}
